version: "3.8"
services:
  production:
    container_name: docker-react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
#  client:
#    stdin_open: true
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    ports:
#      - "4000:4000"
#    volumes:
#      - "home/app/node_modules"
#      - "./:/home/app"